import React, { useState } from 'react';

const FormularioCasamento = () => {
  const [advogadoNome, setAdvogadoNome] = useState('');
  const [advogadoRG, setAdvogadoRG] = useState('');
  const [noivoNome, setNoivoNome] = useState('');
  const [noivoCPF, setNoivoCPF] = useState('');
  const [noivaNome, setNoivaNome] = useState('');
  const [noivaCPF, setNoivaCPF] = useState('');
  const [regimeDeBens, setRegimeDeBens] = useState('');
  const [novoNomeNoivo, setNovoNomeNoivo] = useState('');
  const [novoNomeNoiva, setNovoNomeNoiva] = useState('');
  const [observacoes, setObservacoes] = useState('');
  const [confirmado, setConfirmado] = useState(false);

  const handleConfirmation = () => {
    // Lรณgica para confirmar os dados do formulรกrio
    setConfirmado(true);
  };

  return (
    <div style={{ backgroundColor: '#ff0b48', padding: '20px', borderRadius: '10px' }}>
      <h1 style={{ textAlign: 'center', color: '#fff' }}>๐ FORMULรRIO DE CASAMENTO ๐</h1>
      <form>
        <label>Nome do advogado(a) responsรกvel:</label>
        <input type="text" value={advogadoNome} onChange={(e) => setAdvogadoNome(e.target.value)} />
        
        <label>RG do Advogado (a) responsรกvel:</label>
        <input type="text" value={advogadoRG} onChange={(e) => setAdvogadoRG(e.target.value)} />
        
        <label>Nome do Noivo:</label>
        <input type="text" value={noivoNome} onChange={(e) => setNoivoNome(e.target.value)} />
        
        <label>CPF do Noivo:</label>
        <input type="text" value={noivoCPF} onChange={(e) => setNoivoCPF(e.target.value)} />
        
        <label>Nome da Noiva:</label>
        <input type="text" value={noivaNome} onChange={(e) => setNoivaNome(e.target.value)} />
        
        <label>CPF da Noiva:</label>
        <input type="text" value={noivaCPF} onChange={(e) => setNoivaCPF(e.target.value)} />
        
        <label>Calendรกrio:</label>
        <input type="date" />
        
        <label>REGIME DE BENS DO CASAMENTO:</label>
        <select value={regimeDeBens} onChange={(e) => setRegimeDeBens(e.target.value)}>
          <option value="">Selecione...</option>
          <option value="COMUNHรO TOTAL DE BENS">COMUNHรO TOTAL DE BENS</option>
          <option value="COMUNHรO PARCIAL DE BENS">COMUNHรO PARCIAL DE BENS</option>
          <option value="SEPARAรรO TOTAL DE BENS">SEPARAรรO TOTAL DE BENS</option>
        </select>
        
        <label>NOME QUE CADA UM DOS CรNJUGES PASSA A UTILIZAR:</label>
        <input type="text" placeholder="Nome do Noivo" value={novoNomeNoivo} onChange={(e) => setNovoNomeNoivo(e.target.value)} />
        <input type="text" placeholder="Nome da Noiva" value={novoNomeNoiva} onChange={(e) => setNovoNomeNoiva(e.target.value)} />
        
        <label>OBSERVAรรES/AVERBAรรES:</label>
        <textarea value={observacoes} onChange={(e) => setObservacoes(e.target.value)} />
        
        <button type="button" onClick={handleConfirmation}>Confirmar</button>
      </form>
      {confirmado && (
        <div>
          {/* ๐น Data e hora automรกtica */}
          <p>Data: {new Date().toLocaleDateString()}</p>
          <p>Hora: {new Date().toLocaleTimeString()}</p>
          
          {/* Caixa de texto fixa */}
          <p style={{ textAlign: 'center' }}>
            โโโโโโโโโโโโโโโโโโโง โข โงโโโโโโโโโโโโโโโโโ<br />
            โ๏ธ SEM MAIS PARA O MOMENTO, A PARTIR DESTA DATA DECLARO ASSIM CASADOS EM MATRIMรNIO OS CIDADรOS SUPRAMENCIONADOS.โ๏ธ<br />
            โโโโโโโโโโโโโโโโโโโโโโง โข โงโโโโโโโโโโโโ
          </p>
        </div>
      )}
    </div>
  );
};

export default FormularioCasamento;
